### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by keech** [akikgt/gbemu#1]
@akikgt 
昔、五反田のオフィスで話した中村です！
forkwellでたまたまプロフィールを見かけたので、ご連絡しました。

よかったら、facebookなどでフレンド申請していただけませんか？

よろしくお願いします！

**Comment by akikgt** [comment]
@keech 
ご無沙汰しています！
はい！facebookのリクエストを送りました

**Comment by keech** [comment]
👍

**Comment by keech** [comment]
@akikgt ご無沙汰しています！元気にしています？
